---

- name : Create websocket-server local directories
  become: true
  file:
    path: "{{ item }}" 
    state: directory
    recurse: true
  with_items:
    - "{{ websocket_server_bin_location }}"
    - "{{ websocket_server_data_location }}"

- name : Copy websocket-server jar file to local directory
  become: true
  copy:
    src: files/WebSocket-server-0.1.0.jar
    dest: "{{ websocket_server_bin_location }}/WebSocket-server-0.1.0.jar"

- name : Copy websocket-server Dockerfile to local directory
  become: true
  copy:
    src: files/Dockerfile
    dest: "{{ websocket_server_bin_location }}/Dockerfile"

- name: Build websocket-server image
  become: true
  docker_image:
     path: "{{ websocket_server_bin_location }}"
     name: websocket-server

- name : Start or restart websocket-server container
  become: true
  docker_container:
    name: websocket-server
    image: websocket-server
    volumes:
      - "{{ websocket_server_data_location }}:/data/todo"
